# Generated by Django 4.1 on 2022-08-26 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_rename_toppings_topping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topping',
            old_name='name',
            new_name='topping',
        ),
    ]
