# Generated by Django 4.1 on 2022-08-26 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0003_rename_name_topping_topping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topping',
            old_name='topping',
            new_name='pizza_topping',
        ),
    ]
